name: "RSpec Report"
description: "A GitHub Action that report RSpec failure."
author: "aki77"
inputs:
  token:
    description: "Github token"
    required: true
  json-path:
    description: "JSON File path"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
